name: MySQL Backup to S3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight; adjust as needed.

jobs:
  mysql_backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start

      - name: Configure MySQL Root User
        env:
          MYSQL_ROOT_PASSWORD: root_password
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$MYSQL_ROOT_PASSWORD';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Create MySQL Database
        run: |
          mysql -u root -p root_password -e "CREATE DATABASE zuns;"

      - name: Backup MySQL Database
        run: |
          mysqldump -u root -p root_password zuns > zuns_backup.sql

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Upload to S3
        run: |
          aws s3 cp zuns_backup.sql s3://zun069/zuns_backup.sql
